#Load Libraries

library(tidyverse)
library(vtable)
library(readxl)
library(readr)
library(writexl)
library(openxlsx)
library(knitr)
library(dplyr)
library(psych)
library(pastecs)
library(gtsummary)
library(ggrepel)
library(doBy)
library(ggthemes)
library(ggplot2)
library(ggcorrplot)
library(FinCal)
library(MonteCarlo)
library(MASS)
library(reshape2)
library(scatterplot3d)
library(plotly)
library(sf)
library(tmap)
library(leaflet)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
library(rnaturalearthhires)
library(maps)
library(cowplot)
library(grid)
library(ggridges)


